import PortfolioLayout from '../components/PortfolioLayout';

export default function WebDesign() {
    const items = [
    { title: 'Portfolio Project 1', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_0.jpg' },
    { title: 'Portfolio Project 2', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_1.jpg' },
    { title: 'Portfolio Project 3', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_10.jpg' },
    { title: 'Portfolio Project 4', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_11.jpeg' },
    { title: 'Portfolio Project 5', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_12.jpg' },
    { title: 'Portfolio Project 6', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_13.jpg' },
    { title: 'Portfolio Project 7', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_14.jpg' },
    { title: 'Portfolio Project 8', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_15.jpg' },
    { title: 'Portfolio Project 9', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_16.jpg' },
    { title: 'Portfolio Project 10', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_17.png' },
    { title: 'Portfolio Project 11', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_18.png' },
    { title: 'Portfolio Project 12', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_19.jpg' },
    { title: 'Portfolio Project 13', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_2.jpeg' },
    { title: 'Portfolio Project 14', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_20.jpg' },
    { title: 'Portfolio Project 15', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_21.jpg' },
    { title: 'Portfolio Project 16', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_22.jpeg' },
    { title: 'Portfolio Project 17', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_23.jpg' },
    { title: 'Portfolio Project 18', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_24.jpeg' },
    { title: 'Portfolio Project 19', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_25.jpg' },
    { title: 'Portfolio Project 20', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_26.jpg' },
    { title: 'Portfolio Project 21', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_27.jpeg' },
    { title: 'Portfolio Project 22', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_28.jpeg' },
    { title: 'Portfolio Project 23', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_29.jpg' },
    { title: 'Portfolio Project 24', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_3.jpg' },
    { title: 'Portfolio Project 25', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_30.jpeg' },
    { title: 'Portfolio Project 26', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_31.jpg' },
    { title: 'Portfolio Project 27', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_32.jpg' },
    { title: 'Portfolio Project 28', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_33.jpeg' },
    { title: 'Portfolio Project 29', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_34.jpg' },
    { title: 'Portfolio Project 30', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_35.jpeg' },
    { title: 'Portfolio Project 31', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_36.jpeg' },
    { title: 'Portfolio Project 32', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_37.jpeg' },
    { title: 'Portfolio Project 33', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_38.jpg' },
    { title: 'Portfolio Project 34', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_39.jpeg' },
    { title: 'Portfolio Project 35', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_4.jpeg' },
    { title: 'Portfolio Project 36', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_40.jpg' },
    { title: 'Portfolio Project 37', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_41.jpg' },
    { title: 'Portfolio Project 38', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_42.jpeg' },
    { title: 'Portfolio Project 39', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_43.jpeg' },
    { title: 'Portfolio Project 40', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_44.jpg' },
    { title: 'Portfolio Project 41', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_45.jpg' },
    { title: 'Portfolio Project 42', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_46.jpg' },
    { title: 'Portfolio Project 43', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_5.jpg' },
    { title: 'Portfolio Project 44', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_6.jpg' },
    { title: 'Portfolio Project 45', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_7.jpeg' },
    { title: 'Portfolio Project 46', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_8.jpg' },
    { title: 'Portfolio Project 47', desc: 'Detailed view of the project work.', image: '/images/portfolio/web_design/full_img_9.jpg' }
  ];
  return <PortfolioLayout title="Web Design" subtitle="Crafting beautiful, functional, and intuitive digital experiences for modern brands." items={items} />;
}
